### ISSUE TITLE
support msg.topic

### ISSUE THREAD

**Issue by paxinos** [MeowWolf/node-red-contrib-amqp#10]
Would it be possible to support msg.topic in both the in and out nodes?

If present on the output node it would override the routing.topic selected .

And on the input node the topic would be included in the output as msg.topic.

Thanks!

**Comment by amodelbello** [comment]
Hi @paxinos, thanks for the suggestion. I'm not sure I understand the need for a new topic field on the msg object. Could you maybe describe a use case that this change would solve?

**Comment by paxinos** [comment]
Greetings.

We may subscribe to multiple topics or even '#'.  We then want to be able to respond with the correct topic if we need to send a message.

For example, if we have a chat bot listening on a queue, we need to be able to send a response back to the correct topic (user)

Or if we are listening on a firehose, we need to know if the message is 'publish', 'deliver',...  and that is only sent on the topic.

for a messaging, we have one message topic exchange and each app can only listen on their own 'topic' (enforced by auth) and need to be able to send to other app's 'topic'

Does this help?

**Comment by amodelbello** [comment]
Thanks @paxinos,
Couldn't the logic you're describing be built with additional nodes, i.e. function or switch? I'm not sure I understand the benefit of adding a new field to the message object.

**Comment by paxinos** [comment]
Because we want to send messages to specific topics.  And only nodes listening to those topics receive the message.   No need to light up a lot of CPU time just to determine the messages isn't relevant.    It is a matter of efficiency.

On example is a network of over 1000 pi's.   We should be able to address each Pi by Topic.  They all don't need to receive messages that are not relevant for them.  This saves a lot on network bandwidth.

We are also using this for a private messaging system - users are 'topics'.   Each user should only receive messages for them and not for other users.    So we need to both send by topic.  and listen (programmatically) to only our own topic by specifying it when registering.   

This all works fine with other AMQP nodes.    Unfortunately (as of a month ago) only your AMQP node works with newer nodejs versions...  and it is the only one that works with the latest docker container builds.

I can send you the files as I've modified for amqp out.. If I can build a diff I will...  I was in a hurry at the time and actually edited the 'built' .js instead of the .ts files...

**Comment by amodelbello** [comment]
Okay. Why don't you submit a pull request then. I'll probably be able to understand more easily with a code example.

**Comment by namtab00** [comment]
Hi.

I'm queuing on this issue to request support of an **options** property on the output, as already done on https://github.com/node-red-tools/node-red-contrib-amqp.

I'm stuck between your package not supporting **topic + options**, and _node-red-tools/node-red-contrib-amqp._ needing to be installed as a global package...

**Comment by amodelbello** [comment]
Hi @namtab00. We've developed a need for this internally as well. I'm planning on adding this feature within the next few weeks.

**Comment by namtab00** [comment]
@amodelbello Cool, I'll be keeping a close eye on this issue, and probably try the new version as soon as it becomes available on npm.

**Comment by paxinos** [comment]
Just checking on time frame for this update?   

Another problem I have is the node doesn't reconnect if the connection drops.  I'm still using an older release that I hacked to support msg.topic so this might have already been addressed.

**Comment by namtab00** [comment]
@amodelbello Any chance of an ETA on the next release ?

When **@meowwolf/node-red-contrib-amqp** finally supports specifying an _options_ property on output, so that _headers_ and _messageId_  can be specified (NServiceBus + rabbitmq requirements, FWIMC), I can finally ditch **@node-red-tools/node-red-contrib-amqp@^2.0.1** (which MUST be installed globally and does not provide a globally configurable broker node).

So this will greatly simplify things not only at flow design time, but mainly during deployment in a Docker container..

**Comment by amodelbello** [comment]
As a matter of fact I'm going to start work on it this week. My goal is to get this node to v1 status within the next two weeks. This (support msg.topic #10) is the most pressing issue out of all the stuff I want to get done so I will try to tackle it first. I would expect something within the next few days.

**Comment by amodelbello** [comment]
@paxinos - I'm finally getting started on this. After rereading your original issue above I'm a little confused by:
> And on the input node the topic would be included in the output as msg.topic.

I plan to add a `topic` string field and a `properties` json field as acceptable input to the AMQP Out node. The topic will override the routing key and the properties field will serve as the AMQP properties object including the headers object.

As the AMQP In node receives actual amqp messages, not arbitrary objects that we can shape, wouldn't it make sense to send a "topic" value as a header field into the AMQP In node that can then be converted to a `topic` field when being passed back through an AMQP Out node?

Let me know if this works for your use case or if I'm just misunderstanding.

**Comment by paxinos** [comment]
I'm fine either way.   but to be consistent with other amqp nodes, adding
msg.topics on the input node would make it easier for those trying your
node.   but doesn't matter to me.

**Comment by amodelbello** [comment]
Fixed by https://github.com/MeowWolf/node-red-contrib-amqp/pull/16

**Comment by amodelbello** [comment]
@paxinos I wanted to give you a heads up that the latest release (v1.0.1) has a breaking change regarding the topic input field. I've changed the field name from `topic` to `routingKey`. I felt that it's more consistent to use routingKey since that's what the field is actually overriding. Since the original change adding the topic input only went in couple days ago I figure this should have minimal impact.
