### ISSUE TITLE
Incorrect handling of routing keys when closing a connection.

### ISSUE THREAD

**Issue by amodelbello** [MeowWolf/node-red-contrib-amqp#12]
When we bind a queue we do this:
```
this.parseRoutingKeys().forEach(routingKey => {
    this.channel.bindQueue(this.q.queue, name, routingKey)
})
```
creating a separate binding for each key

When we unbind a queue we do this:
```
await this.channel.unbindQueue(queueName, exchangeName, routingKey)
```
just sending the key or keys to the unbind function in one call. We need to add a forEach function that unbinds the same way we bind.

**Comment by xiic** [comment]
Can confirm this bug. But if "Auto Delete" of a queue is disabled, I would expect that the binding would stay in place (so the messages are still delivered to the queue, even if Node-RED was shut down).

**Comment by amodelbello** [comment]
Fixed with:
https://github.com/MeowWolf/node-red-contrib-amqp/pull/17
