### ISSUE TITLE
Control enabled of AMQP-in by msg.enabled or at specified intervals like a cronjob

### ISSUE THREAD

**Issue by UNOPARATOR** [MeowWolf/node-red-contrib-amqp#26]
What I would like to achieve is this:

- If an error occurs during the processing of a message from an *AMQP in Manual ACK* node, I return the flow with the original msg to ACK the message and using an "AMQP out" to move the message to an error queue.
  - **Retry the message in the error queue by moving them to the original queue as a cron job (every X hours, at specific times etc) by enabling an "AMQP in" consuming the error queue but only enabled by the cron job's trigger.**
- If no error is occured just ACK the message and be done with it.

What do you think @amodelbello ?

**Comment by UNOPARATOR** [comment]
bump?

**Comment by amodelbello** [comment]
Hi @UNOPARATOR,
Apologies for the super late response.
This sounds like a cool idea. Did it work for you?

**Comment by UNOPARATOR** [comment]
No problem.

Since you haven't released a new version, the current version doesn't allow me to do that _(enable/disable the AMQP-in node)_.
I'm not a node.js guy, so providing a PR for this would be difficult for me which was the reason for asking it in the first place (I hoped it might get picked if it would be beneficial for you too in any way).

**Comment by UNOPARATOR** [comment]
@pauldeng, would you like to have a go at this issue too? ;)

**Comment by pauldeng** [comment]
I am not quite understand this requirement.

My understanding is you try to limit the rate of retry a failed message. With the nack feature, you can simply delay the nack to the interval you prefer. After the interval, failed message is nack and requeued.

Please give my [nack demo](https://github.com/MeowWolf/node-red-contrib-amqp/issues/25#issuecomment-900207735) a try. In this demo, message re-try is set to every 20 seconds (the delay node):
![nack-demo](https://dengpeng.de/wp-content/uploads/2021/08/node-red-amqp-nack-link.jpg)

**Comment by UNOPARATOR** [comment]
That wouldn't be covering my need to use a queue as a batch job queue: `(every X hours, at specific times etc)`
You might think it as scheduled processing at specific times only which would make the messages in the queue consumed only for a brief period.
Whatever the usage is, what I need is to be able to change the enabled property of the consumer node, so that until the consumer is enabled again, the new messages would keep on waiting on the queue.

**Comment by amodelbello** [comment]
@UNOPARATOR I may be misunderstanding your use case here but couldn't what you describe be accomplished with a simple Delay node? If an error occurs during message processing just send it back to the original flow via an amqp out node but with a delay in front of it.

**Comment by pauldeng** [comment]
I think what you want is manually control the node to connect or disconnect from RabbitMQ server.

The amqp-in-manual-ack node would be the best candidate to have this feature. Perhaps, when it receives a msg.manualConn, it will connect/disconnect accordingly. You need to setup your own cron outside of this node to trigger this message.

Is it make sense to you? @UNOPARATOR

**Comment by UNOPARATOR** [comment]
@pauldeng, that is exactly what I tried to explain.
But the amqp-in-manual-ack node needs the original message to ACK the message as input. According to your example if msg.manualConn is added and used, then this should be set in the last message to disconnect the connection, right? What if the last message fails?
Too bad, Node-RED doesn't allow multiple inputs for nodes.

**Comment by UNOPARATOR** [comment]
> @UNOPARATOR I may be misunderstanding your use case here but couldn't what you describe be accomplished with a simple Delay node? If an error occurs during message processing just send it back to the original flow via an amqp out node but with a delay in front of it.

Come to think of it that might work, but wouldn't that mean message loss in case of a Node-RED restart?

**Comment by pauldeng** [comment]
Well, not exactly has to be the original message. At the moment, the manual-ack node is trying to stay connected. We can set a flag there to stop reconnecting if a msg.manulConn is injected. Perhaps it could be a solution. Unfortunately, I am not that familiar with that part of code and @amodelbello would be the best person.

If Node-Red restart, you will not lose any message. As not acked message will be requeue when Node-Red disconnect from RabbitMQ.

**Comment by amodelbello** [comment]
@UNOPARATOR I don't think messing with the node's connection is the right way to go. I would suggest trying to filter or limit the amqp-in node's input instead.

**Comment by UNOPARATOR** [comment]
Thanks for your time & valuable inputs.
I'm closing this issue now.
