### ISSUE TITLE
Add support for VirtualHost in amqp-broker

### ISSUE THREAD

**Issue by UNOPARATOR** [MeowWolf/node-red-contrib-amqp#3]
Currently the only possible way to specify the virtual host is by adding ```/virtualhostname```after the port number. This gives a warning when deploying the flow but it works nevertheless.

**Comment by amodelbello** [comment]
Thanks for pointing this out @UNOPARATOR. Let me know how this works for you.

**Comment by UNOPARATOR** [comment]
It works fine, thank you for your quick response. =)
