### ISSUE TITLE
Reconnect timeout

### ISSUE THREAD

**Issue by capIdxItaly** [MeowWolf/node-red-contrib-amqp#31]
Hello.
I have a probelm with this set of nodes.
A couple weeks ago, during the change of time from winter to summer, our AMQP server went down and this node disconnected trom the server. After that, it didn't reconnect when the mentioned server went back online. We had to manually re-deploy the nodes to let them connect to the AMQP server. 
Same thing appened yesterday, the AMQP server went down for a different cause, but the connection didn't come back online on it's own.
 
Is this a bug? 

Are we missing something in the configurations?
this is the config node:
![image](https://user-images.githubusercontent.com/82083689/117123125-ef836f00-ad96-11eb-9576-c4e4d608f22d.png)

and this is one of the nodes that uses said config node:
![image](https://user-images.githubusercontent.com/82083689/117123295-248fc180-ad97-11eb-944a-ca23fb66b94e.png)

thanks for your help

**Comment by amodelbello** [comment]
@capIdxItaly I'm currently working on a possible solution for this. The amqp nodes do have an auto-reconnect feature that will reconnect the node to the broker if it goes down temporarily. Evidently this does not work in all cases. I have't been able to nail down a reliable way to reproduce the issue yet either.

When your server went down were the credentials still saved in the config node? Also, how long was the server down before it came back up? 

I'll keep you posted on any developments on my end.

**Comment by amodelbello** [comment]
@capIdxItaly I just published v2.0.0. I think this solves the issue. Once you have a chance to install it please let me know how it works for you.

**Comment by capIdxItaly** [comment]
@amodelbello 

> When your server went down were the credentials still saved in the config node? 
yes, the only thing i had to do was re-deploy the flow and it started again, no other steps

> how long was the server down before it came back up?
I don't know, it was during the night and we found it only because the AMQP nodes were down.

>  I just published v2.0.0. I think this solves the issue.
Thanks, i'll try the new version as soon as I can

**Comment by amodelbello** [comment]
fyi - I just pushed out a new patch version because I accidentally used deprecated event names. 

`2.0.1` is the version to install now.
