### ISSUE TITLE
amqp out node converts xml object to string

### ISSUE THREAD

**Issue by ashok0617** [MeowWolf/node-red-contrib-amqp#41]
- amqp out node stringifies the payload before publishing to amqp which stops sending data as object. 
- I tried sending xml. the double quote handled with escape char \" and whole content as string. My other end parser failing because of this
- I modified amqp out as attached here that works

![image](https://user-images.githubusercontent.com/75435866/133898640-2c594cab-e331-49d8-83f1-d220b3c239db.png)

Can this changes be submitted?

**Comment by ashok0617** [comment]
I understand that the latest version changed from js to ts but payload still being stringified. The similar change would be needed to support normal object or other format like xml which will be handled based on amqp properties config type.

**Comment by amodelbello** [comment]
@ashok0617 Would you mind sending me an example of the xml you're trying to send (with escaped quotes)? 

And also an example flow that shows how the message breaks when it's stringified?

**Comment by ashok0617** [comment]
@amodelbello, please find attached test result with xml
[test-result.docx](https://github.com/MeowWolf/node-red-contrib-amqp/files/7221880/test-result.docx)
