### ISSUE TITLE
Exchange name setting is totally ignored in Amqp Out

### ISSUE THREAD

**Issue by cloud-rocket** [MeowWolf/node-red-contrib-amqp#44]
The messages go to `amq.direct` exchange regardless of the configuration

**Comment by ashok0617** [comment]
i don't see this issue. As you can see the exchange in attached screenshot as amq.topic
https://user-images.githubusercontent.com/75435866/135193997-344a9224-40bc-4420-a3a5-bdc7dd6fd457.png

**Comment by ashok0617** [comment]
> The messages go to `amq.direct` exchange regardless of the configuration
@cloud-rocket any specific settings? Pls see below test screen. I can see the exchange name as amq.topic

**Comment by cloud-rocket** [comment]
Checked again, it was my fault - the problem is different. I am trying to interface RPC server which is implemented by a different system. And it was failing, because Exchange is asserted with `autoDelete=false`, while in the other system it is created with `true`. I'll maybe try to create a PR with a configurable `autoDelete` option (which is currently not addressed at all).
