### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by cloud-rocket** [MeowWolf/node-red-contrib-amqp#50]
Hi guys - this package is better than others in my opinion, but is it possible to add a license to it?

Otherwise, it cannot be used/improved.

Thanks

**Comment by amodelbello** [comment]
@cloud-rocket thanks for the kind words! I will look into choosing an appropriate license.

**Comment by amodelbello** [comment]
@cloud-rocket - so turns out we had an ISC license included all along. Maybe you missed it because it was further down in the package.json file? I just pushed a v2.4.2 tag that moves the license field up to be right under the name field.
